### PR TITLE
Added constants as it is required

### PR DESCRIPTION
**Pull request by rubiin**
Added constants as it is required to be used on inject

### CODE REVIEW

**Comment by johnbiundo** [comment]
@rubiin Thanks!  I won't be able to look at this for a day or two, FYI.

**Comment by rubiin** [comment]
Anytime mate

**Comment by rubiin** [comment]
@johnbiundo  did you check it?

**Comment by johnbiundo** [comment]
Thanks @rubiin.  I'll publish shortly.

**Comment by rubiin** [comment]
cool then. I will use the latest release

**Pull request merged**
